require:
  - rubocop-rake
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  DisplayStyleGuide: true
  Exclude:
    - db/schema.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/ConditionalAssignment:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - bin/**/*

Metrics/PerceivedComplexity:
  Exclude:
    - bin/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*

Metrics/MethodLength:
  Exclude:
    - bin/**/*
